spring:
   datasource:
      url: jdbc:mysql://localhost:3306/signin?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&AllowPublicKeyRetrieval=true
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: syl199746
server:
   port: 2828